<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_standard_userlocked_out_userproblem_use_f4ae4b</name>
   <tag></tag>
   <elementGuidId>3d1c67d4-33d8-4a34-94e1-9b66ec92db85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.bot_column</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c1cf2ec5-879a-40d9-a94e-418a398388c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bot_column</value>
      <webElementGuid>a7b4e4a6-8719-43e3-8b09-ca451ef6e461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;login_wrapper&quot;]/div[@class=&quot;login_wrapper-inner&quot;]/div[@class=&quot;bot_column&quot;]</value>
      <webElementGuid>abdc4671-88c9-4a18-a458-eb7c5ab83925</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div[2]</value>
      <webElementGuid>10657f9e-ffea-4b87-9d46-cc50d335e21a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>646728c7-daad-4cf2-a6f9-babbdfafdb71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
